name: AI Signal Generator

on:
  schedule:
    - cron: '0,15,30,45 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Manual trigger

jobs:
  generate_signals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Explicitly install PyTorch with CUDA support
          pip install torch==1.12.0+cpu torchvision==0.13.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
      
      - name: Fetch latest OHLCV data
        run: |
          # Add the current directory to PYTHONPATH
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python src/utils/fetch_data.py
      
      - name: Generate signals
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          export USE_SIMULATION_MODE=true
          python main.py
      
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/signals.json
          git add tradingview/signals.js
          git diff --quiet && git diff --staged --quiet || git commit -m "Update trading signals [automated]"
          git push